Alterações e Correções
jacksonlmp/agiota_web pull request #12
Opened 2024-07-23 18:08 UTC by Yasmiinmuniz

"Troca na Exceção de criarLembrete"
"Organização, ajustes e adição de funções do emprestimo na fachada" "Rota em Transacao para o método listarTransacoesPorEmprestimo" "Troca de Exessão em Transacao"
"Remoção do @joincolumn de transação"
"Remoção do método ListarParcelas(), pois retornava" "Organização da ParcelaService"

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva requested changes
Modificar também título do PR para se referir às features implementadas

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/LembreteController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
Substituir por status de bad request

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/TransacaoController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
Substituir por bad request

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/LembreteDTO.java
> +    public Lembrete toEntity() {
Refatorar para "toLembrete" para seguir padrão dos outros DTOs

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/TransacaoDTO.java
> +    public Transacao criarTransacao(Parcela parcela) {
Refatorar pra "toTransacao" pra seguir padrão dos outros DTOs

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/LembreteDTO.java
> +public class LembreteDTO {
Adicionar validações de campos

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/LembreteDTO.java
> +        return lembrete;
Em vez de obter o atributo com o "this", utilizar método "get"

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/TransacaoDTO.java
> +        transacao.setParcela(parcela);
Em vez de obter o atributo com o "this", utilizar método "get"

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/basica/Lembrete.java
> +    private long usuarioId;
Remover atributo daqui e do DTO.
O lembrete está vinculado a uma parcela, que pertence a um empréstimo do usuário, então já existe essa relação.

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/LembreteDTO.java
> +    private long usuarioId;
Remover atributo

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/basica/Transacao.java
> +    @OneToOne
O relacionamento está com a cardinalidade diferente da que foi modelada no diagrama

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/ParcelaService.java
> +        Optional<Parcela> parceOpt = parcelaRepository.findById(id);
```suggestion
        Optional<Parcela> parcelaOpt = parcelaRepository.findById(id);
```

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/LembreteService.java
> +        }
Remover trecho de código. O DTO não chegará nulo

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/TransacaoService.java
> +import br.edu.ufape.agiota.fachada.exceptions.RegistroJaExistenteException; // Importar a exceção de registro já existente
Remover comentário

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/TransacaoService.java
> +public class TransacaoService implements TransacaoServiceInterface {
A interface implementada não existe. 
Criar considerando [pedidos de alterações realizados no PR antigo](https://github.com/jacksonlmp/agiota_web/pull/6/files/4b748423663757a23cec4ce1b7a3914a4628f4bc).

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/ParcelaService.java
> +public class ParcelaService implements ParcelaServiceInterface {
A interface implementada não existe. 
Criar considerando [pedidos de alterações realizados no PR antigo](https://github.com/jacksonlmp/agiota_web/pull/6/files/4b748423663757a23cec4ce1b7a3914a4628f4bc).

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/LembreteService.java
> +public class LembreteService implements LembreteServiceInterface {
A interface implementada não existe

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/TransacaoService.java
> +    public Transacao criarTransacao(TransacaoDTO transacaoDTO) throws RegistroJaExistenteException {
```suggestion
    public Transacao criarTransacao(TransacaoDTO transacaoDTO) throws RegistroNaoEncontradoException {
```

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/TransacaoService.java
> +    public Transacao criarTransacao(TransacaoDTO transacaoDTO) throws RegistroJaExistenteException {
Corrigir nos locais onde estiver lançando a exceção ao chamar o método

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/fachada/Fachada.java
> +    private TransacaoServiceInterface transacaoService;
Interfaces inexistentes

2024-07-23 20:11 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/basica/Transacao.java
> +import jakarta.persistence.JoinColumn;
Remover import não utilizado

2024-08-07 15:19 UTC, Yasmiinmuniz commented on src/main/java/br/edu/ufape/agiota/controllers/TransacaoController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());

2024-08-07 15:19 UTC, Yasmiinmuniz commented on src/main/java/br/edu/ufape/agiota/controllers/LembreteController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());

2024-08-07 15:35 UTC, Yasmiinmuniz commented on src/main/java/br/edu/ufape/agiota/dtos/LembreteDTO.java
> +    public Lembrete toEntity() {
public Lembrete toLembrete() {

2024-08-07 15:39 UTC, Yasmiinmuniz commented on src/main/java/br/edu/ufape/agiota/dtos/LembreteDTO.java
> +        return lembrete;
public Lembrete toLembrete() {
        Lembrete lembrete = new Lembrete();
        lembrete.setData(getData());
        lembrete.setTexto(getTexto());
        lembrete.setUsuarioId(getUsuarioId());
        return lembrete;
    }

2024-08-07 15:40 UTC, Yasmiinmuniz commented on src/main/java/br/edu/ufape/agiota/dtos/LembreteDTO.java
> +public class LembreteDTO {
@NotNull(message = "A data não pode ser nula")
    private Date data;

    @NotBlank(message = "O texto não pode estar em branco")
    private String texto;

    @Positive(message = "O ID da parcela deve ser um valor positivo")
    private long parcelaId;
    
    @Positive(message = "O ID do usuário deve ser um valor positivo")
    private long usuarioId;

2024-08-07 15:41 UTC, Yasmiinmuniz commented on src/main/java/br/edu/ufape/agiota/dtos/LembreteDTO.java
> +    private long usuarioId;
Qual, linha 13 tá vázia

2024-08-07 21:05 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/LembreteDTO.java
> +        return lembrete;
Isso, no caso, você corrige no arquivo, commita e dá um push novamente

2024-08-07 21:05 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/LembreteDTO.java
> +    public Lembrete toEntity() {
No caso, a alteração deve ser no arquivo e enviado para cá novamente. O comentário é apenas para sinalizar onde modificar

2024-08-07 21:06 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/LembreteController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
Alterar no arquivo e submeter novamente

2024-08-07 21:12 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/LembreteDTO.java
> +    private long usuarioId;
O usuarioID, ele não existe no [diagrama](https://app.diagrams.net/#G1z2zDCg6Epr3hfUI6Akz01zsEcm8m7wYf#%7B%22pageId%22%3A%22C5RBs43oDa-KdzZeNtuy%22%7D) da classe lembrete, como sinalizado nesse [report](https://github.com/jacksonlmp/agiota_web/pull/12/files#r1688535308)

2024-08-10 20:46 UTC, Yasmiinmuniz commented on src/main/java/br/edu/ufape/agiota/negocio/services/LembreteService.java
> +        }
@Override
public Lembrete criarLembrete(LembreteDTO lembreteDTO) throws RegistroJaExistenteException {
    Lembrete lembrete = lembreteDTO.toEntity();
    Optional<Parcela> parcelaOpt = parcelaRepository.findById(lembreteDTO.getParcelaId());

    if (!parcelaOpt.isPresent()) {
        throw new RegistroNaoEncontradoException("Parcela com o identificador " + lembreteDTO.getParcelaId() + " não foi encontrada!");
    }

    lembrete.setParcela(parcelaOpt.get());
    return lembreteRepository.save(lembrete);
}

2024-08-13 23:17 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/LembreteController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND).body(e.getMessage());
@Yasmiinmuniz

2024-08-13 23:29 UTC, ThiagoCavalcantiSilva requested changes

2024-08-13 23:29 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/ParcelaService.java
> +    }
Método não utilizado. Removê-lo caso não haja necessidade.
Se for usar no futuro, então o método do repository deve ser refatorado para receber o id do empréstimo também, fazendo a consulta diretamente no banco em vez de filtrar no código.

2024-08-13 23:29 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/interfaces/ParcelaServiceInterface.java
> +    Parcela buscarParcela(long id, long emprestimoId);
Remover método não utilizado.

2024-08-13 23:33 UTC, ThiagoCavalcantiSilva requested changes

2024-08-13 23:33 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/interfaces/TransacaoServiceInterface.java
> +    Transacao criarTransacao(TransacaoDTO transacaoDTO) throws RegistroJaExistenteException, RegistroNaoEncontradoException;
Remover 'RegistroNaoEncontradoException' do método e também da importação da classe

2024-08-16 03:21 UTC, ThiagoCavalcantiSilva requested changes

2024-08-16 03:21 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/AgiotaLembreteController.java
> +            System.out.println(agiotaId);
Remover prints

2024-08-16 03:21 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/fachada/Fachada.java
> +    public List<Lembrete> listarLembretesPorUsuarioId(long agiotaId) {
Refatorar para "listarLembretesPorAgiotaId"

2024-08-20 00:06 UTC, ThiagoCavalcantiSilva requested changes
Alterar também título do PR, para se referir às features desenvolvidas

2024-08-20 00:06 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/AgiotaLembreteController.java
> +    public ResponseEntity<?> listarLembretesPorUsuarioId(@PathVariable long agiotaId) {
```suggestion
    public ResponseEntity<?> listarLembretesPorAgiotaId(@PathVariable long agiotaId) {
```

2024-08-20 00:06 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/interfaces/TransacaoServiceInterface.java
> +    Transacao criarTransacao(TransacaoDTO transacaoDTO) throws RegistroJaExistenteException, RegistroNaoEncontradoException;
Remover 'RegistroNaoEncontradoException' do método e também da importação da classe

2024-08-20 15:39 UTC, ThiagoCavalcantiSilva approved these changes

2024-08-20 16:14 UTC, merged