Implementação componentes de Login e Cadastro
jacksonlmp/agiota_web pull request #18
Opened 2024-08-21 02:42 UTC by Yasmiinmuniz

Implementação componentes de Login e Cadastro e adiciona configuração de API

- Adiciona componente Login
- Adiciona componente Cadastro
- Configura API para login e cadastro
- Atualiza App.js para gerenciar rotas e alert entre Login e Cadastro

2024-08-21 12:33 UTC, luiz-davi-m requested changes

2024-08-21 12:33 UTC, luiz-davi-m commented on agiota_front_end/src/api.js
> +const API_URL = 'http://localhost:3000/users';
Essa rota não existe

2024-08-22 00:51 UTC, luiz-davi-m requested changes

2024-08-22 00:51 UTC, luiz-davi-m commented on agiota_front_end/src/api.js
> +    const response = await axios.post(`${API_URL}/cadastro`, user);
essa rota não existe. Para criar um usuário, apenas através do cliente e do agiota. Basta o olhar no insomnia as requisições que estão em: Usuario > Agiota > Criar agiota **e** Usuario > Cliente > Criar Cliente

2024-08-22 01:05 UTC, luiz-davi-m requested changes

2024-08-22 01:05 UTC, luiz-davi-m commented on agiota_front_end/src/index.js
> -            { path: "/emprestimos", element: <Emprestimos /> }
voltar as rotas como estavam antes, apenas adiconar as novas que vc criou e as lógices necesárias

2024-09-04 15:48 UTC, jacksonlmp reviewed
Adicionado validação no campo de CPF:
- Tamanho
- Formato
![image](https://github.com/user-attachments/assets/1b3aab6a-b36e-4c9c-bca6-8de1102622c8)

2024-09-04 16:43 UTC, jacksonlmp reviewed
- Validação no campo de senha (mínimo 6 digitos)
- Botão **Próximo** só habilitado se todos os campos forem preenchidos
![image](https://github.com/user-attachments/assets/2e6dfc3e-5154-4390-a6eb-0a8343fc53cd)

2024-09-04 20:11 UTC, jacksonlmp reviewed
Agora é possível cadastrar Agiota normalmente:
Front:
![image](https://github.com/user-attachments/assets/55abb2e1-ed7d-4f15-b9e5-f977acfb28df)
API:
![image](https://github.com/user-attachments/assets/df52c21a-9a59-4530-a6eb-c8a49a8353b7)

2024-09-18 22:36 UTC, ThiagoCavalcantiSilva approved these changes

2024-09-18 22:36 UTC, merged