Criando recursos de emprestimo para o cliente
jacksonlmp/agiota_web pull request #5
Opened 2024-07-11 20:39 UTC by luiz-davi-m

2024-07-11 21:56 UTC, ThiagoCavalcantiSilva requested changes

2024-07-11 21:56 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/EmprestimoService.java
> +        emprestimo.setAgiota(agiota);
Transferir pro DTO, passando as informações via parâmetro

2024-07-11 21:56 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/EmprestimoService.java
> +            throw new RegistroNaoEncontradoException("Emprestimo não encontrado para esse o identificar " + id);
```suggestion
            throw new RegistroNaoEncontradoException("Emprestimo não encontrado para o identificador " + id);
```

2024-07-11 21:56 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/ClienteService.java
> +            throw new EmailJaCadastradoException("3 se encontra cadastrado no sistema");
Ajustar mensagem de erro

2024-07-11 21:56 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/fachada/exceptions/NaoPermitidoException.java
> +public class NaoPermitidoException extends RuntimeException {
```suggestion
public class OperacaoNaoPermitidaException extends RuntimeException {
```

2024-07-11 21:56 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/basica/Emprestimo.java
> +        switch (getStatus()) {
Refatorar switch:

public void checarPossibilidadeDeCancelar() {
    switch (getStatus()) {
        case APROVADO -> throw new NaoPermitidoException("O emprestimo não pode ser cancelado, pois já foi aprovado");
        case QUITADO -> throw new NaoPermitidoException("O emprestimo não pode ser cancelado, pois já foi quitado");
        case ATRASADO -> throw new NaoPermitidoException("O emprestimo não pode ser cancelado, pois está sendo pago");
        case REJEITADO -> throw new NaoPermitidoException("O emprestimo não pode ser cancelado, pois foi recusado pelo agiota");
        case CANCELADO -> throw new NaoPermitidoException("O emprestimo não pode ser cancelado, pois já foi cancelado");
        default -> { }
    }
}

2024-07-11 21:56 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/fachada/Fachada.java
> +    public Cliente criarCliente(ClienteDTO clienteDTO) throws EmailJaCadastradoException, SenhaNulaException {
Utiizar a exceção existente ("RegistroJaExistenteException")

2024-07-11 21:56 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/fachada/Fachada.java
> +    //    Cliente
Remover comentário

2024-07-11 21:56 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/fachada/Fachada.java
> +    //    Emprestimo - Cliente
Remover comentário

2024-07-11 21:56 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/fachada/exceptions/EmailJaCadastradoException.java
> +public class EmailJaCadastradoException extends RuntimeException {
Excluir classe e utilizar a existente

2024-07-11 21:56 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/EmprestimoClienteDTO.java
> +    @NotNull()
Remover parênteses inutilizados das anotações

2024-07-11 22:40 UTC, jacksonlmp commented on src/main/java/br/edu/ufape/agiota/fachada/Fachada.java
> +    //    Cliente
Comentário

2024-07-11 22:40 UTC, jacksonlmp commented on src/main/java/br/edu/ufape/agiota/fachada/Fachada.java
> +    //    Emprestimo - Cliente
Comentário

2024-07-12 02:08 UTC, ThiagoCavalcantiSilva approved these changes

2024-07-12 02:09 UTC, merged