Adição das funcionalidades de parcela e lembrete
jacksonlmp/agiota_web pull request #6
Opened 2024-07-11 23:05 UTC by Yasmiinmuniz

controller, service, repository e fachada

2024-07-12 02:00 UTC, jacksonlmp commented on src/main/java/br/edu/ufape/agiota/controllers/LembreteController.java
> +        } catch (RegistroNaoEncontradoException e) {
Lançar outra exceção por exemplo, "RegistroJaExistenteException".
Não é o caso de não encontrar registro

2024-07-12 02:00 UTC, jacksonlmp commented on src/main/java/br/edu/ufape/agiota/controllers/TransacaoController.java
> +        } catch (RegistroNaoEncontradoException e) {
Lançar outra exceção por exemplo, "RegistroJaExistenteException".
Não é o caso de não encontrar registro

2024-07-12 02:00 UTC, jacksonlmp commented on src/main/java/br/edu/ufape/agiota/dtos/TransacaoDTO.java
> +	private Date data;
Corrigir espaçamento

2024-07-12 02:00 UTC, jacksonlmp commented on src/main/java/br/edu/ufape/agiota/dtos/TransacaoDTO.java
> +	private Parcela parcela;
Corrigir espaçamento

2024-07-12 02:00 UTC, jacksonlmp commented on src/main/java/br/edu/ufape/agiota/fachada/Fachada.java
> +}
Colchete a mais, impedindo o projeto de rodar

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva requested changes

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/LembreteController.java
> +    public List<Lembrete> listarLembrete() {
Deveria buscar lembretes apenas de um usuário.
Verificar feature de avaliar reputação e replicar o código.

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/ParcelaController.java
> +    public List<Parcela> listarParcelas() {
Deveria buscar lembretes apenas de um empréstimo.
Verificar feature de avaliar reputação e replicar o código.

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on git
Remover arquivo vazio

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on FETCH_HEAD
Remover arquivo vazio

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/ParcelaController.java
> +            Parcela parcela = (Parcela) fachada.buscarTransacoesPorParcela(id);
A conversão para parcela está incorreta. O método retorna uma lista de transações, não há como ser convertido em parcela.
Ajustar o método chamado e criar um endpoint em TransacaoController para buscar as transações da parcela.

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/LembreteDTO.java
> +    }
Remover getters (já estão contidos na anotação @Data do lombok).
Adicionar anotações de validação no DTO e o @Valid no controller que o utiliza.

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/TransacaoDTO.java
> +    }
Remover getters e setters, pois a classe já está anotada com @Data.

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/fachada/Fachada.java
Retornar o código removido de outras features (services e métodos de agiota e avaliação).

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/basica/Lembrete.java
> +	}
Remover método e import da lista.

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/interfaces/TransacaoServiceInterface.java
> +	List<Transacao> listarTransacao();
Não será necessário listar todas as transações de todos os usuários/empréstimos/parcelas. Deverá listar transações de um determinado empréstimo, por exemplo.

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/interfaces/TransacaoServiceInterface.java
> +    Transacao criarTransacao(TransacaoDTO transacaoDTO) throws RegistroNaoEncontradoException;
Substituir exceção pela "RegistroJaExistenteException"

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/interfaces/ParcelaServiceInterface.java
> +	}
Remover método, pois não segue o padrão e apenas devolve uma lista nula.

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/interfaces/LembreteServiceInterface.java
> +    List<Lembrete> listarLembrete();
Deve filtrar pelo usuarioId.

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/interfaces/LembreteServiceInterface.java
> +    Lembrete atualizarLembrete(LembreteDTO lembreteDTO, long id) throws RegistroNaoEncontradoException;
Não será necessário atualizar lembretes.

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/interfaces/LembreteServiceInterface.java
> +    Lembrete criarLembrete(LembreteDTO lembreteDTO) throws RegistroNaoEncontradoException;
Utilizar a "RegistroJaExistenteException"

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/basica/Transacao.java
> +
Remover getters e setters

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/basica/Transacao.java
> +    public void setParcela(Parcela parcela) {
Remover método set

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/basica/Transacao.java
> +    @JoinColumn(name = "parcela_id")
Substituir o joinColumn pela anotação de relacionamento com cardinalidade (@OneToOne, @OneToMany, @ManyToOne ou @ManyToMany).

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/ParcelaService.java
> +        return parcelaRepository.findAll();
Filtrar pelo empréstimo

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/LembreteService.java
> +        return lembreteRepository.findAll();
Filtrar pelo usuário

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/LembreteService.java
> +        throw new RegistroNaoEncontradoException("Lembrete com o identificador " + id + " não foi encontrada!");
```suggestion
        throw new RegistroNaoEncontradoException("Lembrete com o identificador " + id + " não foi encontrado!");
```

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/LembreteService.java
> +        return lembreteRepository.save(lembrete);
O nome do método não se refere ao contexto da classe.
E o corpo do método atualiza o objeto que acabou de consultar do banco, sem fazer alterações nele.

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/LembreteService.java
> +	}
Remover métodos, pois não foram implementados

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/TransacaoController.java
> +@RequestMapping("/transacao")
Colocar nome no plural (e ajustar na coleção do insomnia)

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/TransacaoController.java
> +    }
Filtrar pelo empréstimo ou parcela, a depender do que fizer mais sentido

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/TransacaoService.java
> +    }
Nâo deve listar todas as transações existentes, deve filtrar por algo (usuário ou empréstimo, por exemplo). A depender de como o sistema será arquitetado

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/TransacaoService.java
> +    public Transacao criarTransacao(TransacaoDTO transacaoDTO) throws RegistroNaoEncontradoException {
Substituir por "RegistroJaExistenteException"

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/TransacaoService.java
> +
Mover alteraçõs dos atributos para dentro do DTO

2024-07-12 02:44 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/ParcelaDTO.java
Remover arquivo não utilizado

2024-07-16 19:18 UTC, Yasmiinmuniz commented on src/main/java/br/edu/ufape/agiota/negocio/basica/Transacao.java
> +
certeza?

2024-07-16 23:43 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/basica/Transacao.java
> +
SIm, já estão inclusos na anotação "@Data" do lombok.

2024-07-17 05:07 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/TransacaoController.java
> +    }
Ainda não resolvido

2024-07-17 05:07 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/TransacaoService.java
> +    }
Ainda não resolvido

2024-07-17 05:07 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/basica/Transacao.java
> +    @JoinColumn(name = "parcela_id")
Ainda não resolvido

2024-07-17 05:08 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/interfaces/ParcelaServiceInterface.java
> +	}
Ainda não resolvido

2024-07-17 05:08 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/fachada/Fachada.java
Ainda não resolvido

2024-07-17 05:10 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/interfaces/TransacaoServiceInterface.java
> +	List<Transacao> listarTransacao();
Ainda não resolvido

2024-07-17 05:12 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/ParcelaController.java
> +            Parcela parcela = (Parcela) fachada.buscarTransacoesPorParcela(id);
Faltou criar a rota em TransacaoController chamando o método "buscarTransacoesPorParcela", que ficou sem uso na fachada

2024-07-17 05:17 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/TransacaoController.java
> +        } catch (RegistroNaoEncontradoException e) {
Ainda não resolvido

2024-07-17 05:17 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/controllers/LembreteController.java
> +        } catch (RegistroNaoEncontradoException e) {
A observação seria na rota de criar lembrete, porém, ainda não foi resolvido

2024-07-17 17:49 UTC, merged