Criando endpoints para que o agiota gerencie os seus emprestimos
jacksonlmp/agiota_web pull request #8
Opened 2024-07-16 12:38 UTC by luiz-davi-m

2024-07-17 17:08 UTC, jacksonlmp approved these changes

2024-08-15 15:04 UTC, ThiagoCavalcantiSilva requested changes

2024-08-15 15:04 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/services/EmprestimoService.java
> +            throw new RegistroNaoEncontradoException("Emprestimo não encontrado");
```suggestion
            throw new RegistroNaoEncontradoException("Empréstimo não encontrado");
```

2024-08-15 15:04 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/negocio/basica/Emprestimo.java
> +
Adicionar acento nas aparições de "empréstimo"

2024-08-15 15:04 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/AprovarEmprestimoDTO.java
> +        emprestimo.setDataDeVencimento(getDataDeVencimento()    );
Ajustar espaçamento dos parênteses

2024-08-15 15:04 UTC, ThiagoCavalcantiSilva commented on src/main/java/br/edu/ufape/agiota/dtos/AprovarEmprestimoDTO.java
> +    public void toAprovarEmprestimo(Emprestimo emprestimo, double taxaDeJuros) {
O nome do método está similar a uma conversão de tipos. Substitui por algo como "aprovar", "confirmarEmprestimo", etc.

2024-08-15 16:35 UTC, ThiagoCavalcantiSilva approved these changes

2024-08-15 16:36 UTC, merged